import AboutComponent from '@/components/About';
import BannerComponent from '@/components/Banner';
import ClientComponent from '@/components/Clients';
import DownloadComponent from '@/components/Download';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import PricingComponent from '@/components/Pricing';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white h-full'>
        <Header />
        <BannerComponent
          heading={'Explore your world with field robo'}
          description={`Field Robo has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`}
        />
        <AboutComponent 
          heading={'About Field Robo'}
          description={`All-In-One Platform. Total Visibility. Our field service management
          software is feature rich and supports a wide range of businesses who
          perform service jobs, project and maintenance management.`}
      
        />
        <ClientComponent />
        <PricingComponent />
        <DownloadComponent />
        <Footer />
      </main>
    </>
  );
}
