import AboutComponent from '@/components/About';
import BannerComponent from '@/components/Banner';
import ClientComponent from '@/components/Clients';
import DownloadComponent from '@/components/Download';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import PricingComponent from '@/components/Pricing';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white h-full'>
        <Header />
        <BannerComponent
          heading={'Explore your world with Field Robo'}
          description={`Optimize your business flow, Empower your team to excel and Leave lasting impressions on your customers`}
        />
        <AboutComponent
          heading={`All-In-One Platform.
          Total Visibility.`}
          description={`Real-time visibility, intelligent features and all the information for your team in one place. Field Robo is your all-in-one platform for job management, scheduling, planned maintenance, invoicing, quoting, automated communications, reporting and more.`}
          text={`Our field service management software is feature rich and supports a wide range of businesses who perform service jobs, project and maintenance management.`}
        />
        <ClientComponent />
        <PricingComponent />
        <DownloadComponent />
        <Footer />
      </main>
    </>
  );
}
