import AboutComponent from '@/components/About';
import BannerComponent from '@/components/Banner';
import ClientComponent from '@/components/Clients';
import DownloadComponent from '@/components/Download';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import PricingComponent from '@/components/Pricing';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white h-full'>
        <Header />
        <BannerComponent/>
        <AboutComponent />
        <ClientComponent />
        <PricingComponent />
        <DownloadComponent />
        <Footer/>
      </main>
    </>
  );
}
